// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyalymcmcufrnnbkqkmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5YWx5bWNtY3Vmcm5uYmtxa21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDUxMDYsImV4cCI6MjA3MDAyMTEwNn0.cpGxpvlMvwxG1qEXPjBOad-3nOAl05kXoWlra_n4geA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});